defaults:
  - files: default
  - roiloc: default_corot2
  - segmentation: bagging_accurate
  - augmentation: default
  - multispectrality: default
  - hardware: onnxruntime
  - override hydra/help: hsf
